spring:
   datasource:
      url: jdbc:mysql://localhost:3306/driver_stat
      username: driver_stat
      password: driver_stat
      
   jpa:
      hibernate: 
         ddl-auto: update
      show-sql: true